version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
before_build:
- cmd: nuget restore src/ParquetAdla.sln
build:
  project: src/Parquet.Adla/Parquet.Adla.csproj
  verbosity: minimal
after_build:
- ps: .\src\deploy.ps1
test: off